version: '3.8'

services:
  app:
    container_name: qb
    image: osiru/qb:${BACKEND_TAG}
    working_dir: /usr/src/app
    ports:
      - "9070:9070"
    depends_on:
      - postgres
    environment:
      - ENV=production
      - DEBUG=0
      - DJANGO_SECRET_KEY=django-insecure-fmq&5@^#yv*$lmqc8o+q(_#v)_9n#&u*_=lwz+=ty^@)6b@v=m
      - USE_S3=0
      - ALLOWED_HOST=*
      - POSTGRES_USER=steve
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - DB_IGNORE_SSL=true
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/0
      - CELERY_IGNORE_RESULT=1
      - CELERY_SEND_EVENTS=1
      - CELERYD_SEND_EVENTS=1
      - CELERY_RESULT_PERSISTENT=1
      - CELERY_ACKS_LATE=1
      - CELERY_TIMEZONE=Africa/Nairobi
      - CELERY_TASK_RESULT_EXPIRES=3600
    volumes:
      - .:/usr/src/app
      - qb_uploads:/var/www/qb/
      - ./staticfiles:/usr/src/app/staticfiles
      - qb_logs:/var/log/qb
    networks:
      - qb_app_net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.5"

  postgres:
    image: postgres:14
    ports:
      - "5439:5432"
    volumes:
      - qb_app_pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - qb_app_net
    deploy:
      resources:
        limits:
          memory: 1G


volumes:
  qb_app_pg:
  qb_logs:
    driver: local
  qb_uploads:
    driver: local

networks:
  qb_app_net:
    driver: bridge
